[2mdn.net] HTTPSConnectionPool(host='2mdn.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf71ba61e0>: Failed to resolve '2mdn.net' ([Errno -5] No address associated with hostname)"))
[a-msedge.net] HTTPSConnectionPool(host='a-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf7182eff0>: Failed to resolve 'a-msedge.net' ([Errno -5] No address associated with hostname)"))
[a2z.com] HTTPSConnectionPool(host='a2z.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf718222d0>: Failed to resolve 'a2z.com' ([Errno -5] No address associated with hostname)"))
[aaplimg.com] HTTPSConnectionPool(host='aaplimg.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf7182cfb0>: Failed to resolve 'aaplimg.com' ([Errno -5] No address associated with hostname)"))
[adnxs.com] HTTPSConnectionPool(host='adnxs.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf71822510>: Failed to resolve 'adnxs.com' ([Errno -5] No address associated with hostname)"))
[aiv-cdn.net] HTTPSConnectionPool(host='aiv-cdn.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf71ba5ac0>: Failed to resolve 'aiv-cdn.net' ([Errno -5] No address associated with hostname)"))
[akadns.net] HTTPSConnectionPool(host='akadns.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf7182f5f0>: Failed to resolve 'akadns.net' ([Errno -5] No address associated with hostname)"))
[akamai.net] HTTPSConnectionPool(host='akamai.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf716ff590>: Failed to resolve 'akamai.net' ([Errno -5] No address associated with hostname)"))
[akamaiedge.net] HTTPSConnectionPool(host='akamaiedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf71714e30>: Failed to resolve 'akamaiedge.net' ([Errno -5] No address associated with hostname)"))
[akamaized.net] HTTPSConnectionPool(host='akamaized.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf716feed0>: Failed to resolve 'akamaized.net' ([Errno -5] No address associated with hostname)"))
[amazon-adsystem.com] HTTPSConnectionPool(host='amazon-adsystem.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf71ba65a0>: Failed to resolve 'amazon-adsystem.com' ([Errno -5] No address associated with hostname)"))
[apple-dns.net] HTTPSConnectionPool(host='apple-dns.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf7183a5d0>: Failed to resolve 'apple-dns.net' ([Errno -5] No address associated with hostname)"))
[appsflyersdk.com] HTTPSConnectionPool(host='appsflyersdk.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf6c362390>: Failed to resolve 'appsflyersdk.com' ([Errno -5] No address associated with hostname)"))
[azureedge.net] HTTPSConnectionPool(host='azureedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70e3e750>: Failed to resolve 'azureedge.net' ([Errno -5] No address associated with hostname)"))
[azurewebsites.net] HTTPSConnectionPool(host='azurewebsites.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70e3d6d0>: Failed to resolve 'azurewebsites.net' ([Errno -5] No address associated with hostname)"))
[b-msedge.net] HTTPSConnectionPool(host='b-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70e3d8e0>: Failed to resolve 'b-msedge.net' ([Errno -5] No address associated with hostname)"))
[bytefcdn-oversea.com] HTTPSConnectionPool(host='bytefcdn-oversea.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70a4f2f0>: Failed to resolve 'bytefcdn-oversea.com' ([Errno -5] No address associated with hostname)"))
[bytefcdn-ttpeu.com] HTTPSConnectionPool(host='bytefcdn-ttpeu.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70a70e60>: Failed to resolve 'bytefcdn-ttpeu.com' ([Errno -5] No address associated with hostname)"))
[cdn77.org] HTTPSConnectionPool(host='cdn77.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf71717290>: Failed to resolve 'cdn77.org' ([Errno -5] No address associated with hostname)"))
[cdninstagram.com] HTTPSConnectionPool(host='cdninstagram.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70a71cd0>: Failed to resolve 'cdninstagram.com' ([Errno -5] No address associated with hostname)"))
[cloudapp.net] HTTPSConnectionPool(host='cloudapp.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70a4f2f0>: Failed to resolve 'cloudapp.net' ([Errno -5] No address associated with hostname)"))
[cloudfront.net] HTTPSConnectionPool(host='cloudfront.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf71756330>: Failed to resolve 'cloudfront.net' ([Errno -5] No address associated with hostname)"))
[demdex.net] HTTPSConnectionPool(host='demdex.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf7159e0c0>: Failed to resolve 'demdex.net' ([Errno -5] No address associated with hostname)"))
[dns.cn] HTTPSConnectionPool(host='dns.cn', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdf71953a10>, 'Connection to dns.cn timed out. (connect timeout=None)'))
[domaincontrol.com] HTTPSConnectionPool(host='domaincontrol.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdf71951910>: Failed to establish a new connection: [Errno 111] Connection refused'))
[edgekey.net] HTTPSConnectionPool(host='edgekey.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf711d5940>: Failed to resolve 'edgekey.net' ([Errno -5] No address associated with hostname)"))
[edgesuite.net] HTTPSConnectionPool(host='edgesuite.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf7104a4b0>: Failed to resolve 'edgesuite.net' ([Errno -5] No address associated with hostname)"))
[ggpht.com] HTTPSConnectionPool(host='ggpht.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf7182d460>: Failed to resolve 'ggpht.com' ([Errno -5] No address associated with hostname)"))
[googletagservices.com] HTTPSConnectionPool(host='googletagservices.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf6c318500>: Failed to resolve 'googletagservices.com' ([Errno -5] No address associated with hostname)"))
[googleusercontent.com] HTTPSConnectionPool(host='googleusercontent.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf6c31a000>: Failed to resolve 'googleusercontent.com' ([Errno -5] No address associated with hostname)"))
[gtld-servers.net] HTTPSConnectionPool(host='gtld-servers.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf6c35eb40>: Failed to resolve 'gtld-servers.net' ([Errno -5] No address associated with hostname)"))
[gvt1.com] HTTPSConnectionPool(host='gvt1.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf6c35d7c0>: Failed to resolve 'gvt1.com' ([Errno -5] No address associated with hostname)"))
[gvt2.com] HTTPSConnectionPool(host='gvt2.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf6c35e960>: Failed to resolve 'gvt2.com' ([Errno -5] No address associated with hostname)"))
[l-msedge.net] HTTPSConnectionPool(host='l-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf7097cf80>: Failed to resolve 'l-msedge.net' ([Errno -5] No address associated with hostname)"))
[macromedia.com] HTTPSConnectionPool(host='macromedia.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdf70960680>, 'Connection to macromedia.com timed out. (connect timeout=None)'))
[mangosip.ru] HTTPSConnectionPool(host='mangosip.ru', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdf70e12b10>, 'Connection to mangosip.ru timed out. (connect timeout=None)'))
[microsoftonline.com] HTTPSConnectionPool(host='microsoftonline.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf6c361880>: Failed to resolve 'microsoftonline.com' ([Errno -5] No address associated with hostname)"))
[miit.gov.cn] HTTPSConnectionPool(host='miit.gov.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70e12750>: Failed to resolve 'miit.gov.cn' ([Errno -5] No address associated with hostname)"))
[msedge.net] HTTPSConnectionPool(host='msedge.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdf6c36d2e0>, 'Connection to msedge.net timed out. (connect timeout=None)'))
[msftncsi.com] HTTPSConnectionPool(host='msftncsi.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf6c36f6e0>: Failed to resolve 'msftncsi.com' ([Errno -5] No address associated with hostname)"))
[netflix.net] HTTPSConnectionPool(host='netflix.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdf70a4d2b0>, 'Connection to netflix.net timed out. (connect timeout=None)'))
[nflxso.net] HTTPSConnectionPool(host='nflxso.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70a4e270>: Failed to resolve 'nflxso.net' ([Errno -5] No address associated with hostname)"))
[nr-data.net] HTTPSConnectionPool(host='nr-data.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf719df710>: Failed to resolve 'nr-data.net' ([Errno -5] No address associated with hostname)"))
[o365filtering.com] HTTPSConnectionPool(host='o365filtering.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70a35550>: Failed to resolve 'o365filtering.com' ([Errno -5] No address associated with hostname)"))
[office.net] HTTPSConnectionPool(host='office.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf7097c7d0>: Failed to resolve 'office.net' ([Errno -5] No address associated with hostname)"))
[omtrdc.net] HTTPSConnectionPool(host='omtrdc.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf7097f170>: Failed to resolve 'omtrdc.net' ([Errno -5] No address associated with hostname)"))
[rbxcdn.com] HTTPSConnectionPool(host='rbxcdn.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf714a3ef0>: Failed to resolve 'rbxcdn.com' ([Errno -5] No address associated with hostname)"))
[registrar-servers.com] HTTPSConnectionPool(host='registrar-servers.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70bf9340>: Failed to resolve 'registrar-servers.com' ([Errno -5] No address associated with hostname)"))
[root-servers.net] HTTPSConnectionPool(host='root-servers.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf710b7fe0>: Failed to resolve 'root-servers.net' ([Errno -5] No address associated with hostname)"))
[rubiconproject.com] ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[ruidongcloud.com] HTTPSConnectionPool(host='ruidongcloud.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf710b5d90>: Failed to resolve 'ruidongcloud.com' ([Errno -5] No address associated with hostname)"))
[s-msedge.net] HTTPSConnectionPool(host='s-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf710b6ea0>: Failed to resolve 's-msedge.net' ([Errno -5] No address associated with hostname)"))
[safebrowsing.apple] HTTPSConnectionPool(host='safebrowsing.apple', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf710b4a70>: Failed to resolve 'safebrowsing.apple' ([Errno -5] No address associated with hostname)"))
[shifen.com] HTTPSConnectionPool(host='shifen.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdf70d22b40>, 'Connection to shifen.com timed out. (connect timeout=None)'))
[spo-msedge.net] HTTPSConnectionPool(host='spo-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70b1d610>: Failed to resolve 'spo-msedge.net' ([Errno -5] No address associated with hostname)"))
[t-msedge.net] HTTPSConnectionPool(host='t-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70a71d00>: Failed to resolve 't-msedge.net' ([Errno -5] No address associated with hostname)"))
[tiktokcdn-us.com] HTTPSConnectionPool(host='tiktokcdn-us.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf71136810>: Failed to resolve 'tiktokcdn-us.com' ([Errno -5] No address associated with hostname)"))
[tiktokcdn.com] HTTPSConnectionPool(host='tiktokcdn.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf711dd250>: Failed to resolve 'tiktokcdn.com' ([Errno -5] No address associated with hostname)"))
[trafficmanager.net] HTTPSConnectionPool(host='trafficmanager.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf71136e70>: Failed to resolve 'trafficmanager.net' ([Errno -5] No address associated with hostname)"))
[trbcdn.net] HTTPSConnectionPool(host='trbcdn.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'trbcdn.net'. (_ssl.c:1000)")))
[ttlivecdn.com] HTTPSConnectionPool(host='ttlivecdn.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf71137b30>: Failed to resolve 'ttlivecdn.com' ([Errno -5] No address associated with hostname)"))
[wac-msedge.net] HTTPSConnectionPool(host='wac-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70d203e0>: Failed to resolve 'wac-msedge.net' ([Errno -5] No address associated with hostname)"))
[windowsupdate.com] HTTPSConnectionPool(host='windowsupdate.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70e10a10>: Failed to resolve 'windowsupdate.com' ([Errno -5] No address associated with hostname)"))
[ytimg.com] HTTPSConnectionPool(host='ytimg.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdf70920e00>: Failed to resolve 'ytimg.com' ([Errno -5] No address associated with hostname)"))
