[a-msedge.net] HTTPConnectionPool(host='a-msedge.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9de46a810>: Failed to resolve 'a-msedge.net' ([Errno -5] No address associated with hostname)"))
[gtld-servers.net] HTTPConnectionPool(host='gtld-servers.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e448d4d0>: Failed to resolve 'gtld-servers.net' ([Errno -5] No address associated with hostname)"))
[akamaiedge.net] HTTPConnectionPool(host='akamaiedge.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e4380b50>: Failed to resolve 'akamaiedge.net' ([Errno -5] No address associated with hostname)"))
[domaincontrol.com] HTTPConnectionPool(host='domaincontrol.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9e405ec10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[akamai.net] HTTPConnectionPool(host='akamai.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e40314d0>: Failed to resolve 'akamai.net' ([Errno -5] No address associated with hostname)"))
[windowsupdate.com] HTTPConnectionPool(host='windowsupdate.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9de471310>: Failed to resolve 'windowsupdate.com' ([Errno -5] No address associated with hostname)"))
[microsoftonline.com] HTTPConnectionPool(host='microsoftonline.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e41ee1d0>: Failed to resolve 'microsoftonline.com' ([Errno -5] No address associated with hostname)"))
[akadns.net] HTTPConnectionPool(host='akadns.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e41eca90>: Failed to resolve 'akadns.net' ([Errno -5] No address associated with hostname)"))
[l-msedge.net] HTTPConnectionPool(host='l-msedge.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e412f8d0>: Failed to resolve 'l-msedge.net' ([Errno -5] No address associated with hostname)"))
[trafficmanager.net] HTTPConnectionPool(host='trafficmanager.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e35e7790>: Failed to resolve 'trafficmanager.net' ([Errno -5] No address associated with hostname)"))
[nflxso.net] HTTPConnectionPool(host='nflxso.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e412c810>: Failed to resolve 'nflxso.net' ([Errno -5] No address associated with hostname)"))
[netflix.net] HTTPConnectionPool(host='netflix.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9e4061ad0>, 'Connection to netflix.net timed out. (connect timeout=None)'))
[t-msedge.net] HTTPConnectionPool(host='t-msedge.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e3962110>: Failed to resolve 't-msedge.net' ([Errno -5] No address associated with hostname)"))
[163.com] HTTPConnectionPool(host='163.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9e3963410>, 'Connection to 163.com timed out. (connect timeout=None)'))
[s-msedge.net] HTTPConnectionPool(host='s-msedge.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e3d83210>: Failed to resolve 's-msedge.net' ([Errno -5] No address associated with hostname)"))
[aaplimg.com] HTTPConnectionPool(host='aaplimg.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e3b49b10>: Failed to resolve 'aaplimg.com' ([Errno -5] No address associated with hostname)"))
[edgekey.net] HTTPConnectionPool(host='edgekey.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e451f610>: Failed to resolve 'edgekey.net' ([Errno -5] No address associated with hostname)"))
[cloudapp.net] HTTPConnectionPool(host='cloudapp.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e3b44f50>: Failed to resolve 'cloudapp.net' ([Errno -5] No address associated with hostname)"))
[apple-dns.net] HTTPConnectionPool(host='apple-dns.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e43dec90>: Failed to resolve 'apple-dns.net' ([Errno -5] No address associated with hostname)"))
[nih.gov] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[googleusercontent.com] HTTPConnectionPool(host='googleusercontent.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e36a6850>: Failed to resolve 'googleusercontent.com' ([Errno -5] No address associated with hostname)"))
[macromedia.com] HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9e42b8790>, 'Connection to macromedia.com timed out. (connect timeout=None)'))
[office.net] HTTPConnectionPool(host='office.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e401d410>: Failed to resolve 'office.net' ([Errno -5] No address associated with hostname)"))
[ruidongcloud.com] HTTPConnectionPool(host='ruidongcloud.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9de522090>: Failed to resolve 'ruidongcloud.com' ([Errno -5] No address associated with hostname)"))
[csdn.net] HTTPSConnectionPool(host='www.csdn.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb9de5aead0>, 'Connection to www.csdn.net timed out. (connect timeout=None)'))
[registrar-servers.com] HTTPConnectionPool(host='registrar-servers.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9de5afdd0>: Failed to resolve 'registrar-servers.com' ([Errno -5] No address associated with hostname)"))
[cloudfront.net] HTTPConnectionPool(host='cloudfront.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9de58db50>: Failed to resolve 'cloudfront.net' ([Errno -5] No address associated with hostname)"))
[tiktokcdn.com] HTTPConnectionPool(host='tiktokcdn.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e374bd10>: Failed to resolve 'tiktokcdn.com' ([Errno -5] No address associated with hostname)"))
[aiv-cdn.net] HTTPConnectionPool(host='aiv-cdn.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e46617d0>: Failed to resolve 'aiv-cdn.net' ([Errno -5] No address associated with hostname)"))
[gvt1.com] HTTPConnectionPool(host='gvt1.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e37d0810>: Failed to resolve 'gvt1.com' ([Errno -5] No address associated with hostname)"))
[b-msedge.net] HTTPConnectionPool(host='b-msedge.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e37640d0>: Failed to resolve 'b-msedge.net' ([Errno -5] No address associated with hostname)"))
[miit.gov.cn] HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e35eefd0>: Failed to resolve 'miit.gov.cn' ([Errno -5] No address associated with hostname)"))
[health.mil] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[o365filtering.com] HTTPConnectionPool(host='o365filtering.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e354e4d0>: Failed to resolve 'o365filtering.com' ([Errno -5] No address associated with hostname)"))
[msedge.net] HTTPConnectionPool(host='msedge.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9e396f790>, 'Connection to msedge.net timed out. (connect timeout=None)'))
[spo-msedge.net] HTTPConnectionPool(host='spo-msedge.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e33b1bd0>: Failed to resolve 'spo-msedge.net' ([Errno -5] No address associated with hostname)"))
[omtrdc.net] HTTPConnectionPool(host='omtrdc.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e3ad8590>: Failed to resolve 'omtrdc.net' ([Errno -5] No address associated with hostname)"))
[mangosip.ru] HTTPConnectionPool(host='mangosip.ru', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9e3b58150>, 'Connection to mangosip.ru timed out. (connect timeout=None)'))
[trbcdn.net] ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[twimg.com] HTTPConnectionPool(host='twimg.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e3e6a7d0>: Failed to resolve 'twimg.com' ([Errno -5] No address associated with hostname)"))
[edgesuite.net] HTTPConnectionPool(host='edgesuite.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e46a86d0>: Failed to resolve 'edgesuite.net' ([Errno -5] No address associated with hostname)"))
[adnxs.com] HTTPConnectionPool(host='adnxs.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e46d4a10>: Failed to resolve 'adnxs.com' ([Errno -5] No address associated with hostname)"))
[dzeninfra.ru] HTTPConnectionPool(host='dzeninfra.ru', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e46d7890>: Failed to resolve 'dzeninfra.ru' ([Errno -5] No address associated with hostname)"))
[gvt2.com] HTTPConnectionPool(host='gvt2.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e3595f50>: Failed to resolve 'gvt2.com' ([Errno -5] No address associated with hostname)"))
[wsdvs.com] HTTPConnectionPool(host='wsdvs.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9e45f02d0>: Failed to resolve 'wsdvs.com' ([Errno -5] No address associated with hostname)"))
[azurewebsites.net] HTTPConnectionPool(host='azurewebsites.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb9de5a9890>: Failed to resolve 'azurewebsites.net' ([Errno -5] No address associated with hostname)"))
